require:
  - rubocop-performance
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - 'challenger.gemspec'
    - 'spec/**/*'

# For integration testing
RSpec/MultipleExpectations:
  Exclude:
    - 'spec/rubocop_challenger/cli_spec.rb'

RSpec/NestedGroups:
  Max: 4
