# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2

references:
  - &restore_bundle_install_cache
    restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        - v1-dependencies-
  - &bundle_install
    run:
        name: Bundle Install
        command: |
          bundle install --jobs=4 --retry=3 --path vendor/bundle
  - &save_bundle_install_cache
    save_cache:
      paths:
        - ./vendor/bundle
      key: v1-dependencies-{{ checksum "Gemfile.lock" }}

  - &build
    working_directory: ~/repo
    steps:
      - checkout
      - *restore_bundle_install_cache
      - *bundle_install
      - *save_bundle_install_cache
      - run:
          name: Run Rspec
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --format documentation \
                              --color \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              $TEST_FILES
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
      - run:
          name: Rake Build
          command: |
            bundle exec rake build

  - &rubocop
    working_directory: ~/repo
    steps:
      - checkout
      - *restore_bundle_install_cache
      - *bundle_install
      - *save_bundle_install_cache
      - run: bundle exec rubocop

jobs:
  build_on_ruby_2.3:
    docker:
       - image: circleci/ruby:2.3-node-browsers
    <<: *build
  build_on_ruby_2.4:
    docker:
       - image: circleci/ruby:2.4-node-browsers
    <<: *build
  build_on_ruby_2.5:
    docker:
       - image: circleci/ruby:2.5-node-browsers
    <<: *build
  build_on_ruby_latest:
    docker:
       - image: circleci/ruby:latest-node-browsers-legacy
    <<: *build
  rubocop:
    docker:
       - image: circleci/ruby:2.3-node-browsers
    <<: *rubocop
  verify_rubocop_challenge:
    docker:
      - image: circleci/ruby:2.3-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - *restore_bundle_install_cache
      - *bundle_install
      - *save_bundle_install_cache
      - run: bundle exec rake install
      - run:
          name: Verify Rubocop Challenge
          command: |
            bundle exec exe/rubocop_challenger go \
              --email=ryz310@gmail.com \
              --name=ryz310 \
              --mode=random \
              --labels='rubocop challenge' 'in progress' \
              --regenerate-rubocop-todo \
              --no-commit

  rubocop_challenge:
    docker:
      - image: circleci/ruby:2.3-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Rubocop Challenge
          command: |
            gem install -N rubocop_challenger
            rubocop_challenger go \
              --email=ryz310@gmail.com \
              --name=ryz310 \
              --template=./lib/templates/checklist.md.erb \
              --labels='rubocop challenge' 'in progress' \
              --regenerate-rubocop-todo

  release:
    docker:
       - image: circleci/ruby:2.3-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - *restore_bundle_install_cache
      - *bundle_install
      - *save_bundle_install_cache
      - run:
          name: Create Rubygems Credentials
          command: |
            mkdir ~/.gem
            echo -e "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}" > ~/.gem/credentials
            chmod 0600 ~/.gem/credentials
      - run:
          name: Release Gem
          command: |
            git push --set-upstream origin ${CIRCLE_BRANCH}
            bundle exec rake release --trace

workflows:
  version: 2

  commit:
    jobs:
      - build_on_ruby_2.3
      - build_on_ruby_2.4
      - build_on_ruby_2.5
      - build_on_ruby_latest
      - rubocop
      - verify_rubocop_challenge
      - release:
          context: RubyGems API Key
          requires:
            - build_on_ruby_2.3
            - build_on_ruby_2.4
            - build_on_ruby_2.5
            - build_on_ruby_latest
            - rubocop
          filters:
            branches:
              only:
                - production
      - rubocop_challenge:
          requires:
            - release

  challenge:
    triggers:
      - schedule:
          cron: "30 23 * * *" # 8:30am every day (JST)
          filters:
            branches:
              only:
                - master
    jobs:
      - rubocop_challenge
